// <auto-generated />
namespace Superhero_Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Creatingsuperheroestable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Creatingsuperheroestable));
        
        string IMigrationMetadata.Id
        {
            get { return "201903131351038_Creating superheroes table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
